vscode:
  extensions:
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - vscode-icons-team.vscode-icons@9.5.0:dcvbiJm3ipHVkZXodLCtUA==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - felixfbecker.php-intellisense@2.3.13:dIFTPCKFV+ChjvesjnZhCA==